name: Dispatcher
on:
  workflow_run:
    workflows:
      - "Sample Workflow"
    branches:
      - beta
    types:
      - completed

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['ujala-singh/Ubuntu-EC2-Module']
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: trigger_workflow
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "branch": "${{ steps.extract_branch.outputs.BRANCH_NAME }}"
              }
            }
