name: Dispatcher
on:
  workflow_run:
    workflows:
      - "Sample Workflow"
    branches:
      - beta
    types:
      - completed

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['ujala-singh/Ubuntu-EC2-Module']
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # extract branch name
      - name: Get branch name
        if: startsWith(github.ref, 'refs/heads')
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: trigger_workflow
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "branch": "${{ steps.extract_branch.outputs.branch }}"
              }
            }
