name: Create Main Branch PR

on:
  pull_request:
    types:
      - closed

jobs:
  create_main_branch_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check GitHub CLI version
        run: gh --version

      - name: Create Main Branch PR
        run: |
          echo "Starting workflow..."
          if [ "${{ github.event.pull_request.merged }}"=="true" ] && [ "${{ github.event.pull_request.base.ref }}"=="stage" ]; then
            # Extract the PR number from the merged pull request
            PR_NUMBER=$(echo "${{ github.event.pull_request.title }}" | grep -oP '^(\d+)')
            echo "PR_NUMBER: $PR_NUMBER"
            
            # Create a new branch for the main branch, including the PR number
            echo "Checking out to branch main-branch-update-${PR_NUMBER}..."
            git checkout -b main-branch-update-${PR_NUMBER}
            
            # Make changes or use the existing changes
            
            # Commit the changes, including the PR number in the commit message
            echo "Commiting the changes to branch main-branch-update-${PR_NUMBER}..."
            git commit -am "Merge changes from 'stage' to 'main' (PR #$PR_NUMBER)"
            
            # Push the changes to the repository
            echo "Pushing the changes to branch main-branch-update-${PR_NUMBER}..."
            git push origin main-branch-update-${PR_NUMBER}
            
            # Create a pull request with the PR number in the title
            echo "Creating the PR to main branch with branch name as main-branch-update-${PR_NUMBER}..."
            gh pr create --base main --head main-branch-update-${PR_NUMBER} --title "Merge changes from 'stage' to 'main' (PR #$PR_NUMBER)"
          fi
          echo "Workflow completed successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
